shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 8.0
controller_patience: 5.0
conservative_reset_dist: 3.0
planner_frequency: 0.0 # only use rrt if robot gets stuck
oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behaviors: 
  - name: 'clear_costmap_recovery'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'